export type UIArea = "providers"|"agents"|"chat"|"tools"|"integrations"|"mcp"|"skills"|"workspace"|"project"|"setup"|"dialogs";
export type UIState = "loading"|"populated"|"empty"|"validation"|"saving"|"success"|"error"|"restricted"|"disconnected"|"confirmation"|"retry"|"disabled";
export interface UIReferenceScreen {
  id:string;
  area:UIArea;
  sourcePath:string;
  surface:"page"|"tab"|"dialog"|"drawer"|"popover"|"inline-form"|"wizard"|"modal";
  capability:string;
  states:readonly UIState[];
  interactionPatterns:readonly string[];
}
export const UI_REFERENCE_INVENTORY: readonly UIReferenceScreen[] = [
{id:"ai-settings-shell",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/ai-settings-page.tsx",surface:"page",capability:"providers",states:["loading","populated","restricted"],interactionPatterns:["workspace-selector","tabs","role-gating","access-restricted"]},
{id:"ai-connections-tab",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/connections-tab.tsx",surface:"tab",capability:"providers/secrets",states:["loading","populated","empty","validation","saving","success","error"],interactionPatterns:["personal-vs-workspace-scope","oauth","token-form","validate","remove"]},
{id:"ai-model-config",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/model-config-tab.tsx",surface:"tab",capability:"providers",states:["loading","populated","saving","success","error"],interactionPatterns:["source-selection","model-selection","workspace-defaults","user-overrides"]},
{id:"ai-access-control",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/access-control-tab.tsx",surface:"tab",capability:"providers/identity",states:["loading","populated","saving","success","error"],interactionPatterns:["enforce-ai","source-selection","model-visibility"]},
{id:"ai-doable-settings",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/doable-ai-tab.tsx",surface:"tab",capability:"agents/providers",states:["loading","populated","saving","success","error","disabled"],interactionPatterns:["feature-config","admin-gating","persistence"]},
{id:"provider-wizard",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/provider-wizard.tsx",surface:"wizard",capability:"providers/secrets",states:["loading","populated","validation","saving","success","error","retry"],interactionPatterns:["choose","configure","validate","models","search","scope","credential-entry","reset-on-close"]},
{id:"provider-card",area:"providers",sourcePath:"apps/web/src/modules/ai-settings/components/provider-card.tsx",surface:"inline-form",capability:"providers",states:["populated","validation","success","error","disconnected"],interactionPatterns:["health-status","test","actions"]},
{id:"integration-catalog",area:"integrations",sourcePath:"apps/web/src/modules/integrations/integration-catalog.tsx",surface:"page",capability:"integrations",states:["loading","populated","empty","error"],interactionPatterns:["search","categories","pagination","connected-vs-available","refresh"]},
{id:"integration-card",area:"integrations",sourcePath:"apps/web/src/modules/integrations/integration-card.tsx",surface:"inline-form",capability:"integrations",states:["populated","disconnected","saving","success","error"],interactionPatterns:["connect","disconnect","status","actions"]},
{id:"integration-connect-flow",area:"integrations",sourcePath:"apps/web/src/modules/integrations/connect-flow.tsx",surface:"wizard",capability:"integrations/secrets",states:["loading","validation","saving","success","error","retry"],interactionPatterns:["oauth","manual-credentials","enhanced-auth","permissions","resource-selection"]},
{id:"integration-detail-sheet",area:"integrations",sourcePath:"apps/web/src/modules/integrations/integration-detail-sheet.tsx",surface:"drawer",capability:"integrations",states:["loading","populated","disconnected","error"],interactionPatterns:["details","status","actions","close"]},
{id:"mcp-panel",area:"mcp",sourcePath:"apps/web/src/modules/settings/components/mcp-panel.tsx",surface:"page",capability:"mcp",states:["loading","populated","empty","error","disconnected","retry","confirmation"],interactionPatterns:["refresh","active-inactive","test","reconnect","delete"]},
{id:"mcp-add-server",area:"mcp",sourcePath:"apps/web/src/modules/settings/components/mcp-add-server-form.tsx",surface:"inline-form",capability:"mcp/secrets",states:["validation","saving","success","error","retry"],interactionPatterns:["http-stdio","authentication","discovery","oauth-popup","cancel"]},
{id:"skills-rules-panel",area:"skills",sourcePath:"apps/web/src/modules/skills/skills-panel.tsx",surface:"page",capability:"skills/tools",states:["loading","populated","empty","error","saving","success","confirmation"],interactionPatterns:["scope","expand-collapse","create","edit","delete","refresh"]},
{id:"skill-picker",area:"skills",sourcePath:"apps/web/src/modules/skills/skill-picker.tsx",surface:"popover",capability:"skills",states:["populated","empty","error","disabled"],interactionPatterns:["search","manual-vs-auto","outside-click","portal"]},
{id:"skills-rules-settings",area:"skills",sourcePath:"apps/web/src/modules/settings/components/skills-rules-panel.tsx",surface:"inline-form",capability:"skills",states:["loading","populated","empty","saving","success","error","confirmation"],interactionPatterns:["rule-scope","file-patterns","edit-delete"]},
{id:"workspace-knowledge",area:"workspace",sourcePath:"apps/web/src/app/(dashboard)/workspace-settings/workspace-knowledge.tsx",surface:"page",capability:"context/rag",states:["loading","populated","empty","saving","success","error","confirmation"],interactionPatterns:["knowledge-list","editor","create-update-delete"]},
{id:"project-settings",area:"project",sourcePath:"apps/web/src/modules/settings/components/project-settings.tsx",surface:"page",capability:"workspace/sandbox",states:["loading","populated","saving","success","error","confirmation","disabled"],interactionPatterns:["configuration","status","danger-zone"]},
{id:"setup-ai-provider",area:"setup",sourcePath:"apps/web/src/app/setup/steps/Step2AIProvider.tsx",surface:"wizard",capability:"providers",states:["populated","validation","saving","success","error"],interactionPatterns:["provider-selection","oauth","credentials","model-selection","skip"]},
{id:"setup-integrations",area:"setup",sourcePath:"apps/web/src/app/setup/steps/Step4Integrations.tsx",surface:"page",capability:"integrations",states:["populated","saving","success","error","disabled"],interactionPatterns:["collapsible-billing","secret-visibility","plan-defaults","signup-policy"]},
{id:"dashboard-delete-confirmation",area:"dialogs",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-dialogs.tsx",surface:"confirmation",capability:"workspace",states:["confirmation"],interactionPatterns:["single-delete","bulk-delete","cancel"]},
{id:"dashboard-rename-dialog",area:"dialogs",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-dialogs.tsx",surface:"dialog",capability:"workspace",states:["validation","saving","error"],interactionPatterns:["inline-input","enter-to-submit","cancel"]},
{id:"dashboard-move-folder-dialog",area:"dialogs",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-dialogs.tsx",surface:"dialog",capability:"workspace",states:["populated","empty"],interactionPatterns:["folder-selection","root-option"]},
{id:"dashboard-template-preview",area:"dialogs",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-dialogs.tsx",surface:"modal",capability:"workspace",states:["populated","loading","error"],interactionPatterns:["preview","use-template","remix"]},
{id:"dashboard-github-import",area:"dialogs",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-dialogs.tsx",surface:"dialog",capability:"workspace",states:["loading","validation","success","error"],interactionPatterns:["import","authentication","progress"]},
{id:"editor-chat-panel",area:"chat",sourcePath:"apps/web/src/modules/editor/chat/chat-panel.tsx",surface:"page",capability:"agents/chat",states:["loading","populated","empty","error","saving","retry","disabled"],interactionPatterns:["conversation","streaming","tool-events","attachments","stop-retry","context"]},
{id:"editor-chat-message",area:"chat",sourcePath:"apps/web/src/modules/editor/chat/chat-message.tsx",surface:"inline-form",capability:"chat/streaming",states:["populated","error","loading"],interactionPatterns:["streaming-text","thinking","tool-results","artifacts","copy","retry"]},
{id:"editor-tool-call-card",area:"tools",sourcePath:"apps/web/src/modules/editor/chat/tool-call-card.tsx",surface:"inline-form",capability:"tools",states:["loading","populated","success","error","retry"],interactionPatterns:["tool-call","arguments","result","status","expand-collapse"]},
{id:"editor-user-input-card",area:"agents",sourcePath:"apps/web/src/modules/editor/chat/user-input-card.tsx",surface:"modal",capability:"agent/user-input",states:["populated","saving","success","error"],interactionPatterns:["blocking-question","choice","submit","resume-turn"]},
{id:"editor-state-store",area:"chat",sourcePath:"apps/web/src/modules/editor/hooks/use-editor-store.ts",surface:"inline-form",capability:"chat/editor-state",states:["loading","populated","saving","error"],interactionPatterns:["active-session","stream-state","tool-state","preview-state"]},
{id:"dashboard-voice-input",area:"chat",sourcePath:"apps/web/src/app/(dashboard)/dashboard/dashboard-chat-input.tsx",surface:"inline-form",capability:"chat/voice-input",states:["disabled","error","populated"],interactionPatterns:["microphone","permission-error","speech-input","send"]},
];
